packages:
  - apps/*
  - packages/*

catalogs:
  prisma:
    prisma: latest

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - prisma
