name: Build

on:
  push:
    branches:
      - main
      - ci-cd
      - eas

jobs:
  # build_android:
  #   name: Build Android App
  #   type: build
  #   params:
  #     platform: android
  build_ios:
    name: Build iOS App
    type: build
    params:
      platform: ios
