platform :ios do
  lane :beta do
    setup_ci if ENV['CI']
    app_store_connect_api_key(
            issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
            key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
            key_content: ENV['APP_STORE_CONNECT_KEY']
            )
    build_app
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
