platform :ios do
  lane :beta do
    setup_ci if ENV['CI']
    app_store_connect_api_key(
            issuer_id: ENV['ISSUER_ID'],
            key_id: ENV['KEY_ID'],
            key_content: ENV['KEY_CONTENT']
            )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
