default_platform(:ios)
platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/bomberapp.xcodeproj",
      team_id: "56SR3FVFLU", 
      code_sign_identity: "iPhone Distribution",
      profile_name: "match AppStore com.bomberfastpitch.bomberapp"
    )

    match(type: 'appstore')

    # Build the app with explicit provisioning
    build_app(
      workspace: "ios/bomberapp.xcworkspace",
      scheme: "bomberapp",
      xcargs: "-allowProvisioningUpdates",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.bomberfastpitch.bomberapp" => "match AppStore com.bomberfastpitch.bomberapp"
        }
      }
    )
    api_key = app_store_connect_api_key(
      key_id: "P928568HLS",
      issuer_id: "425b5653-6bc0-4e0d-8e8d-a3456d7828d7",
      key_filepath: "/Users/braedon/Downloads/AuthKey_P928568HLS.p8"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      api_key: api_key
    )
  end
end
